-- FIX: Add business_unit_id to ALL Industry tables
-- Handles both existing tables (from 052/018) AND new tables (from 074)

-- Helper: add column only if table exists AND column missing
-- Mining (new tables from 074)
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mining_simper') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mining_simper' AND column_name='business_unit_id') THEN ALTER TABLE mining_simper ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mining_equipment') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mining_equipment' AND column_name='business_unit_id') THEN ALTER TABLE mining_equipment ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mining_production') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mining_production' AND column_name='business_unit_id') THEN ALTER TABLE mining_production ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mining_fuel') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mining_fuel' AND column_name='business_unit_id') THEN ALTER TABLE mining_fuel ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mining_fatigue') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mining_fatigue' AND column_name='business_unit_id') THEN ALTER TABLE mining_fatigue ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mining_safety') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mining_safety' AND column_name='business_unit_id') THEN ALTER TABLE mining_safety ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mining_jsa') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mining_jsa' AND column_name='business_unit_id') THEN ALTER TABLE mining_jsa ADD COLUMN business_unit_id TEXT; END IF; END $$;

-- Estate
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='estate_harvest') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='estate_harvest' AND column_name='business_unit_id') THEN ALTER TABLE estate_harvest ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='estate_blocks') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='estate_blocks' AND column_name='business_unit_id') THEN ALTER TABLE estate_blocks ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='estate_irrigation') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='estate_irrigation' AND column_name='business_unit_id') THEN ALTER TABLE estate_irrigation ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='estate_nursery') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='estate_nursery' AND column_name='business_unit_id') THEN ALTER TABLE estate_nursery ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='estate_transport') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='estate_transport' AND column_name='business_unit_id') THEN ALTER TABLE estate_transport ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='estate_field') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='estate_field' AND column_name='business_unit_id') THEN ALTER TABLE estate_field ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='estate_yield') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='estate_yield' AND column_name='business_unit_id') THEN ALTER TABLE estate_yield ADD COLUMN business_unit_id TEXT; END IF; END $$;

-- Mill (from 052 — already exist)
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mill_boiler') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mill_boiler' AND column_name='business_unit_id') THEN ALTER TABLE mill_boiler ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mill_press') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mill_press' AND column_name='business_unit_id') THEN ALTER TABLE mill_press ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mill_qc_results') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mill_qc_results' AND column_name='business_unit_id') THEN ALTER TABLE mill_qc_results ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mill_packing') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mill_packing' AND column_name='business_unit_id') THEN ALTER TABLE mill_packing ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mill_maintenance') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mill_maintenance' AND column_name='business_unit_id') THEN ALTER TABLE mill_maintenance ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mill_breakdowns') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mill_breakdowns' AND column_name='business_unit_id') THEN ALTER TABLE mill_breakdowns ADD COLUMN business_unit_id TEXT; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='mill_shift') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mill_shift' AND column_name='business_unit_id') THEN ALTER TABLE mill_shift ADD COLUMN business_unit_id TEXT; END IF; END $$;
