-- DELETE ALL DATA — CLEAN SLATE (SAFE VERSION)
-- Only truncates tables that actually exist

DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'admin_division_access') THEN TRUNCATE TABLE admin_division_access CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'ai_conversations') THEN TRUNCATE TABLE ai_conversations CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'ai_documents') THEN TRUNCATE TABLE ai_documents CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'announcements') THEN TRUNCATE TABLE announcements CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'approval_config') THEN TRUNCATE TABLE approval_config CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'approval_instances') THEN TRUNCATE TABLE approval_instances CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'asset_assignments') THEN TRUNCATE TABLE asset_assignments CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'assets') THEN TRUNCATE TABLE assets CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'audit_chain') THEN TRUNCATE TABLE audit_chain CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'audit_log') THEN TRUNCATE TABLE audit_log CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'audit_log_owner') THEN TRUNCATE TABLE audit_log_owner CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'badges') THEN TRUNCATE TABLE badges CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'bu_divisions') THEN TRUNCATE TABLE bu_divisions CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'budget_allocation') THEN TRUNCATE TABLE budget_allocation CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'business_unit_modules') THEN TRUNCATE TABLE business_unit_modules CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'business_units') THEN TRUNCATE TABLE business_units CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'candidate_pipeline') THEN TRUNCATE TABLE candidate_pipeline CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'certifications') THEN TRUNCATE TABLE certifications CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'corporate_licenses') THEN TRUNCATE TABLE corporate_licenses CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'currency_master') THEN TRUNCATE TABLE currency_master CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'daftar_baru') THEN TRUNCATE TABLE daftar_baru CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'disciplinary_records') THEN TRUNCATE TABLE disciplinary_records CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'emergency_procedures') THEN TRUNCATE TABLE emergency_procedures CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'employee_mutations') THEN TRUNCATE TABLE employee_mutations CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'employees_master') THEN TRUNCATE TABLE employees_master CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'estate_blocks') THEN TRUNCATE TABLE estate_blocks CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'estate_field') THEN TRUNCATE TABLE estate_field CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'estate_harvest') THEN TRUNCATE TABLE estate_harvest CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'estate_irrigation') THEN TRUNCATE TABLE estate_irrigation CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'estate_nursery') THEN TRUNCATE TABLE estate_nursery CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'estate_transport') THEN TRUNCATE TABLE estate_transport CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'estate_yield') THEN TRUNCATE TABLE estate_yield CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'exit_interviews') THEN TRUNCATE TABLE exit_interviews CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'external_notification_logs') THEN TRUNCATE TABLE external_notification_logs CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'external_notifications') THEN TRUNCATE TABLE external_notifications CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'facility_requests') THEN TRUNCATE TABLE facility_requests CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'feature_flags') THEN TRUNCATE TABLE feature_flags CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'final_settlements') THEN TRUNCATE TABLE final_settlements CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'harvest_records') THEN TRUNCATE TABLE harvest_records CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'headcount_plans') THEN TRUNCATE TABLE headcount_plans CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_ai_tasks') THEN TRUNCATE TABLE hr_ai_tasks CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_attendance') THEN TRUNCATE TABLE hr_attendance CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_audit_chain') THEN TRUNCATE TABLE hr_audit_chain CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_benefit_catalog') THEN TRUNCATE TABLE hr_benefit_catalog CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_benefits') THEN TRUNCATE TABLE hr_benefits CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_calendar') THEN TRUNCATE TABLE hr_calendar CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_capability') THEN TRUNCATE TABLE hr_capability CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_coaching') THEN TRUNCATE TABLE hr_coaching CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_coaching_catalog') THEN TRUNCATE TABLE hr_coaching_catalog CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_competency_matrix') THEN TRUNCATE TABLE hr_competency_matrix CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_compliance') THEN TRUNCATE TABLE hr_compliance CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_compliance_catalog') THEN TRUNCATE TABLE hr_compliance_catalog CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_critical') THEN TRUNCATE TABLE hr_critical CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_document_types') THEN TRUNCATE TABLE hr_document_types CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_engagement') THEN TRUNCATE TABLE hr_engagement CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_equipment_util') THEN TRUNCATE TABLE hr_equipment_util CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_exit_clearance') THEN TRUNCATE TABLE hr_exit_clearance CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_finance_kpi') THEN TRUNCATE TABLE hr_finance_kpi CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_kpi_calc_log') THEN TRUNCATE TABLE hr_kpi_calc_log CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_kpi_config') THEN TRUNCATE TABLE hr_kpi_config CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_learning') THEN TRUNCATE TABLE hr_learning CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_leave') THEN TRUNCATE TABLE hr_leave CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_medical_checkup') THEN TRUNCATE TABLE hr_medical_checkup CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_monthly_snapshot') THEN TRUNCATE TABLE hr_monthly_snapshot CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_notifications') THEN TRUNCATE TABLE hr_notifications CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_okr_results') THEN TRUNCATE TABLE hr_okr_results CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_okrs') THEN TRUNCATE TABLE hr_okrs CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_org') THEN TRUNCATE TABLE hr_org CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_overtime') THEN TRUNCATE TABLE hr_overtime CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_payroll') THEN TRUNCATE TABLE hr_payroll CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_penalty_matrix') THEN TRUNCATE TABLE hr_penalty_matrix CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_performance') THEN TRUNCATE TABLE hr_performance CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_plantation_harvest') THEN TRUNCATE TABLE hr_plantation_harvest CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_position_skills') THEN TRUNCATE TABLE hr_position_skills CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_preview_data') THEN TRUNCATE TABLE hr_preview_data CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_production_daily') THEN TRUNCATE TABLE hr_production_daily CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_relations') THEN TRUNCATE TABLE hr_relations CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_requests') THEN TRUNCATE TABLE hr_requests CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_safety') THEN TRUNCATE TABLE hr_safety CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_shift_master') THEN TRUNCATE TABLE hr_shift_master CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_shift_swaps') THEN TRUNCATE TABLE hr_shift_swaps CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_skills') THEN TRUNCATE TABLE hr_skills CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_succession') THEN TRUNCATE TABLE hr_succession CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_succession_matrix') THEN TRUNCATE TABLE hr_succession_matrix CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_survey_responses') THEN TRUNCATE TABLE hr_survey_responses CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_surveys') THEN TRUNCATE TABLE hr_surveys CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_talent_catalog') THEN TRUNCATE TABLE hr_talent_catalog CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_task_board') THEN TRUNCATE TABLE hr_task_board CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_tasks') THEN TRUNCATE TABLE hr_tasks CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_training_catalog') THEN TRUNCATE TABLE hr_training_catalog CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_voice') THEN TRUNCATE TABLE hr_voice CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hr_work_schedule') THEN TRUNCATE TABLE hr_work_schedule CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'idx_nrp') THEN TRUNCATE TABLE idx_nrp CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'incentives') THEN TRUNCATE TABLE incentives CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'irrigation_blocks') THEN TRUNCATE TABLE irrigation_blocks CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'legal_documents') THEN TRUNCATE TABLE legal_documents CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'login_attempts') THEN TRUNCATE TABLE login_attempts CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mfa_factors') THEN TRUNCATE TABLE mfa_factors CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mill_boiler') THEN TRUNCATE TABLE mill_boiler CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mill_breakdown') THEN TRUNCATE TABLE mill_breakdown CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mill_breakdowns') THEN TRUNCATE TABLE mill_breakdowns CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mill_maintenance') THEN TRUNCATE TABLE mill_maintenance CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mill_packing') THEN TRUNCATE TABLE mill_packing CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mill_press') THEN TRUNCATE TABLE mill_press CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mill_qc') THEN TRUNCATE TABLE mill_qc CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mill_qc_results') THEN TRUNCATE TABLE mill_qc_results CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mill_shift') THEN TRUNCATE TABLE mill_shift CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mining_equipment') THEN TRUNCATE TABLE mining_equipment CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mining_fatigue') THEN TRUNCATE TABLE mining_fatigue CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mining_fuel') THEN TRUNCATE TABLE mining_fuel CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mining_jsa') THEN TRUNCATE TABLE mining_jsa CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mining_production') THEN TRUNCATE TABLE mining_production CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mining_safety') THEN TRUNCATE TABLE mining_safety CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mining_simper') THEN TRUNCATE TABLE mining_simper CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'module_definitions') THEN TRUNCATE TABLE module_definitions CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'nursery_blocks') THEN TRUNCATE TABLE nursery_blocks CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'offboarding_checklist') THEN TRUNCATE TABLE offboarding_checklist CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'otp_attempts') THEN TRUNCATE TABLE otp_attempts CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'otp_store') THEN TRUNCATE TABLE otp_store CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'performance_notes') THEN TRUNCATE TABLE performance_notes CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'push_subscriptions') THEN TRUNCATE TABLE push_subscriptions CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'rate_limits') THEN TRUNCATE TABLE rate_limits CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'referrals') THEN TRUNCATE TABLE referrals CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'reimbursements') THEN TRUNCATE TABLE reimbursements CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'salary_adjustments') THEN TRUNCATE TABLE salary_adjustments CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'security_audit_log') THEN TRUNCATE TABLE security_audit_log CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'session_store') THEN TRUNCATE TABLE session_store CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'session_tokens') THEN TRUNCATE TABLE session_tokens CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'settings') THEN TRUNCATE TABLE settings CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'shift_assignments') THEN TRUNCATE TABLE shift_assignments CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'shift_swaps') THEN TRUNCATE TABLE shift_swaps CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'simulation_logs') THEN TRUNCATE TABLE simulation_logs CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'simulations') THEN TRUNCATE TABLE simulations CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'sites') THEN TRUNCATE TABLE sites CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'sso_providers') THEN TRUNCATE TABLE sso_providers CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'survey_responses') THEN TRUNCATE TABLE survey_responses CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'system_bootstrap') THEN TRUNCATE TABLE system_bootstrap CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'team_budgets') THEN TRUNCATE TABLE team_budgets CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'timesheets') THEN TRUNCATE TABLE timesheets CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'timezone_master') THEN TRUNCATE TABLE timezone_master CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'transport_dispatch') THEN TRUNCATE TABLE transport_dispatch CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'travel_requests') THEN TRUNCATE TABLE travel_requests CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'user_roles') THEN TRUNCATE TABLE user_roles CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'vacancies') THEN TRUNCATE TABLE vacancies CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'webhook_configs') THEN TRUNCATE TABLE webhook_configs CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'webhook_logs') THEN TRUNCATE TABLE webhook_logs CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'whistleblowers') THEN TRUNCATE TABLE whistleblowers CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'worker_passwords') THEN TRUNCATE TABLE worker_passwords CASCADE; END IF; END $$;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'workforce_simulations') THEN TRUNCATE TABLE workforce_simulations CASCADE; END IF; END $$;

-- Reset sequences
ALTER SEQUENCE IF EXISTS admin_division_access_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS ai_conversations_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS ai_documents_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS announcements_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS approval_config_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS approval_instances_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS asset_assignments_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS assets_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS audit_chain_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS audit_log_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS audit_log_owner_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS badges_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS bu_divisions_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS budget_allocation_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS business_unit_modules_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS business_units_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS candidate_pipeline_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS certifications_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS corporate_licenses_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS currency_master_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS daftar_baru_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS disciplinary_records_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS emergency_procedures_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS employee_mutations_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS employees_master_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS estate_blocks_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS estate_field_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS estate_harvest_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS estate_irrigation_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS estate_nursery_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS estate_transport_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS estate_yield_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS exit_interviews_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS external_notification_logs_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS external_notifications_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS facility_requests_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS feature_flags_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS final_settlements_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS harvest_records_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS headcount_plans_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_ai_tasks_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_attendance_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_audit_chain_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_benefit_catalog_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_benefits_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_calendar_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_capability_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_coaching_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_coaching_catalog_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_competency_matrix_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_compliance_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_compliance_catalog_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_critical_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_document_types_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_engagement_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_equipment_util_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_exit_clearance_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_finance_kpi_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_kpi_calc_log_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_kpi_config_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_learning_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_leave_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_medical_checkup_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_monthly_snapshot_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_notifications_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_okr_results_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_okrs_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_org_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_overtime_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_payroll_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_penalty_matrix_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_performance_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_plantation_harvest_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_position_skills_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_preview_data_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_production_daily_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_relations_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_requests_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_safety_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_shift_master_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_shift_swaps_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_skills_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_succession_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_succession_matrix_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_survey_responses_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_surveys_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_talent_catalog_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_task_board_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_tasks_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_training_catalog_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_voice_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS hr_work_schedule_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS idx_nrp_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS incentives_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS irrigation_blocks_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS legal_documents_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS login_attempts_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mfa_factors_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mill_boiler_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mill_breakdown_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mill_breakdowns_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mill_maintenance_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mill_packing_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mill_press_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mill_qc_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mill_qc_results_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mill_shift_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mining_equipment_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mining_fatigue_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mining_fuel_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mining_jsa_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mining_production_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mining_safety_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS mining_simper_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS module_definitions_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS nursery_blocks_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS offboarding_checklist_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS otp_attempts_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS otp_store_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS performance_notes_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS push_subscriptions_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS rate_limits_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS referrals_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS reimbursements_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS salary_adjustments_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS security_audit_log_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS session_store_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS session_tokens_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS settings_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS shift_assignments_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS shift_swaps_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS simulation_logs_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS simulations_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS sites_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS sso_providers_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS survey_responses_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS system_bootstrap_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS team_budgets_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS timesheets_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS timezone_master_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS transport_dispatch_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS travel_requests_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS user_roles_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS vacancies_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS webhook_configs_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS webhook_logs_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS whistleblowers_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS worker_passwords_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS workforce_simulations_id_seq RESTART WITH 1;

SELECT 'DELETE COMPLETE' AS status;
