-- Pilar 4: Kecerdasan Prediktif & Inovasi (3 AI RPCs)

CREATE OR REPLACE FUNCTION ai_summarize_employee(p_nrp TEXT) RETURNS JSONB AS $$ DECLARE v_emp RECORD; v_perf JSONB; v_att JSONB; v_result JSONB; BEGIN IF NOT authz_check_admin('employee.view_all') THEN RETURN jsonb_build_object('ok', false, 'msg', 'Admin only'); END IF; SELECT nama, divisi, posisi, business_unit INTO v_emp FROM employees_master WHERE nrp=p_nrp; IF NOT FOUND THEN RETURN jsonb_build_object('ok', false, 'msg', 'Employee not found'); END IF; SELECT jsonb_build_object('avg_kpi', ROUND(AVG(kpi_score),1), 'periods', COUNT(*)) INTO v_perf FROM hr_performance WHERE nrp=p_nrp; SELECT jsonb_build_object('attendance_rate', ROUND(COUNT(*) FILTER(WHERE status_hadir='Hadir')::NUMERIC/NULLIF(COUNT(*),0)*100,1)) INTO v_att FROM hr_attendance WHERE nrp=p_nrp AND date >= NOW() - INTERVAL '6 months'; v_result := jsonb_build_object('employee', jsonb_build_object('nrp',p_nrp,'nama',v_emp.nama,'divisi',v_emp.divisi,'posisi',v_emp.posisi), 'performance', COALESCE(v_perf, '{}'::jsonb), 'attendance', COALESCE(v_att, '{}'::jsonb), 'summary', 'Performance summary for ' || v_emp.nama); INSERT INTO audit_log (action, detail, timestamp) VALUES ('AI_SUMMARIZE', jsonb_build_object('nrp',p_nrp)::text, NOW()); RETURN jsonb_build_object('ok', true, 'data', v_result); END; $$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION ai_flight_risk(p_nrp TEXT) RETURNS JSONB AS $$ DECLARE v_tenure_months INT; v_avg_kpi NUMERIC; v_leave_ratio NUMERIC; v_risk TEXT; v_score NUMERIC; BEGIN SELECT EXTRACT(EPOCH FROM (NOW()-tanggal_masuk))/2592000 INTO v_tenure_months FROM employees_master WHERE nrp=p_nrp; SELECT AVG(kpi_score) INTO v_avg_kpi FROM hr_performance WHERE nrp=p_nrp; SELECT cuti_terpakai::NUMERIC/NULLIF(kuota_cuti,0) INTO v_leave_ratio FROM hr_leave WHERE nrp=p_nrp ORDER BY created_at DESC LIMIT 1; v_score := 0; IF COALESCE(v_tenure_months,12) < 6 THEN v_score := v_score + 30; END IF; IF COALESCE(v_avg_kpi,70) < 60 THEN v_score := v_score + 30; END IF; IF COALESCE(v_leave_ratio,0) > 0.8 THEN v_score := v_score + 20; END IF; IF v_score >= 70 THEN v_risk := 'HIGH'; ELSIF v_score >= 40 THEN v_risk := 'MEDIUM'; ELSE v_risk := 'LOW'; END IF; RETURN jsonb_build_object('ok', true, 'nrp', p_nrp, 'risk_score', v_score, 'risk_level', v_risk, 'factors', jsonb_build_object('tenure_months', v_tenure_months, 'avg_kpi', v_avg_kpi, 'leave_ratio', v_leave_ratio)); END; $$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION ai_detect_anomalies() RETURNS JSONB AS $$ BEGIN IF NOT authz_check_admin('employee.view_all') THEN RETURN jsonb_build_object('ok', false, 'msg', 'Admin only'); END IF; RETURN (SELECT jsonb_build_object('ok', true, 'anomalies', COALESCE(jsonb_agg(row_to_json(t)),'[]'::jsonb)) FROM (SELECT nrp, date, status_hadir, menit_terlambat FROM hr_attendance WHERE menit_terlambat > 60 AND date >= NOW()-INTERVAL '30 days' ORDER BY menit_terlambat DESC LIMIT 20) t); END; $$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION ai_summarize_employee(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION ai_flight_risk(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION ai_detect_anomalies() TO authenticated;
