-- ================================================================
-- 172_hardening_grants.sql — HARDENING GRANT EXECUTE (audit ulang pasca-169)
-- End-state deterministik: revoke semua, lalu grant minimal per pemakai.
--   anon          = entry point pra-login saja (Home.jsx pre-auth)
--   authenticated = seluruh RPC yang dipanggil aplikasi src/ (termasuk owner_*,
--                    semua owner_* di-guard is_owner -> non-owner ditolak)
--   service_role  = SEMUA fungsi (edge functions & cron tak bisa patah)
--   TIDAK di-grant ke anon/auth: decrypt_pii & export_* (grant NOL, SD-internal)
-- Verifikasi: kueri di bagian akhir (count per role + fungsi tanpa grant).
-- ================================================================

-- 1) Bersihkan SEMUA grant default/eksplisit (termasuk sisa over-grant 168 ke auth)
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM anon;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM authenticated;

-- 2) service_role: akses penuh (backend internal / cron / edge)
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO service_role;

-- 3) anon: entry pra-login (worker login/OTP/reset + branding + lockout)
-- ── Helper grant yang tahan instalasi dari awal ────────────────────────────────
-- Sebagian fungsi di bawah bisa BELUM ADA pada jalur instalasi dari awal:
--   * worker_update_profile / *_legacy_*  -> objek live tanpa sumber migrasi
--     (AGENTS.md §5.8 SQL-02), sebagian sudah dipensiunkan dengan rename;
--   * get_estate_blocks() lama            -> dipensiunkan di 073 (lihat catatan 073).
-- Dulu satu nama yang hilang membatalkan SELURUH berkas, sehingga fungsi yang
-- seharusnya di-REVOKE justru tetap terbuka. Sekarang tiap GRANT dijalankan
-- terpisah dan kehilangan nama dilaporkan lewat NOTICE, bukan gagal.
DO $grant172$
DECLARE r RECORD; n_missing integer := 0;
BEGIN
  FOR r IN
    SELECT * FROM (VALUES
      ('anon', 'public.change_password(p_nrp text, p_old_password text, p_new_password text)'),
      ('anon', 'public.check_login_lockout(p_identifier text, p_attempt_type text)'),
      ('anon', 'public.generate_admin_otp()'),
      ('anon', 'public.generate_worker_otp(p_nrp text, p_nik text)'),
      ('anon', 'public.generate_worker_otp(p_nrp text, p_nik text, p_password text)'),
      ('anon', 'public.get_branding()'),
      ('anon', 'public.login_worker(p_nrp text, p_nik text, p_password text)'),
      ('anon', 'public.login_worker(p_nrp text, p_password text)'),
      ('anon', 'public.verify_admin_otp(p_code text)'),
      ('anon', 'public.verify_worker_otp(p_nrp text, p_code text)'),
      ('authenticated', 'public.add_okr_result(p_okr_id integer, p_kr text, p_target numeric, p_unit text)'),
      ('authenticated', 'public.add_performance_note(p_nrp text, p_author text, p_type text, p_content text)'),
      ('authenticated', 'public.admin_approve_request(p_id text, p_note text)'),
      ('authenticated', 'public.admin_change_password(p_old_password text, p_new_password text)'),
      ('authenticated', 'public.admin_create_webhook(p_name text, p_url text, p_events text[])'),
      ('authenticated', 'public.admin_deactivate_worker(p_nrp text)'),
      ('authenticated', 'public.admin_delete_webhook(p_id bigint)'),
      ('authenticated', 'public.admin_export_sheet(p_sheet text)'),
      ('authenticated', 'public.admin_get_asset_assignments()'),
      ('authenticated', 'public.admin_get_assets()'),
      ('authenticated', 'public.admin_get_audit_chain()'),
      ('authenticated', 'public.admin_get_audit_log()'),
      ('authenticated', 'public.admin_get_badges()'),
      ('authenticated', 'public.admin_get_budget()'),
      ('authenticated', 'public.admin_get_divisions()'),
      ('authenticated', 'public.admin_get_employee_stats()'),
      ('authenticated', 'public.admin_get_employees()'),
      ('authenticated', 'public.admin_get_exit_interviews()'),
      ('authenticated', 'public.admin_get_external_notifications()'),
      ('authenticated', 'public.admin_get_facility_requests()'),
      ('authenticated', 'public.admin_get_feature_flags()'),
      ('authenticated', 'public.admin_get_kpi_overview()'),
      ('authenticated', 'public.admin_get_kpi_trend()'),
      ('authenticated', 'public.admin_get_leave()'),
      ('authenticated', 'public.admin_get_low_performers()'),
      ('authenticated', 'public.admin_get_master_data()'),
      ('authenticated', 'public.admin_get_okr()'),
      ('authenticated', 'public.admin_get_org_structure()'),
      ('authenticated', 'public.admin_get_overtime()'),
      ('authenticated', 'public.admin_get_payroll(p_nrp text)'),
      ('authenticated', 'public.admin_get_payroll_summary(p_period text)'),
      ('authenticated', 'public.admin_get_pending_requests()'),
      ('authenticated', 'public.admin_get_referrals()'),
      ('authenticated', 'public.admin_get_role_matrix()'),
      ('authenticated', 'public.admin_get_settlements()'),
      ('authenticated', 'public.admin_get_sso_providers()'),
      ('authenticated', 'public.admin_get_timesheet()'),
      ('authenticated', 'public.admin_get_top_performers()'),
      ('authenticated', 'public.admin_get_vacancies()'),
      ('authenticated', 'public.admin_get_webhook_logs()'),
      ('authenticated', 'public.admin_get_webhooks()'),
      ('authenticated', 'public.admin_reject_request(p_id text, p_note text)'),
      ('authenticated', 'public.admin_reset_worker_password(p_nrp text, p_new_password text)'),
      ('authenticated', 'public.admin_set_feature_flag(p_name text, p_enabled boolean)'),
      ('authenticated', 'public.admin_toggle_webhook(p_id bigint, p_active boolean)'),
      ('authenticated', 'public.admin_update_idea_status(p_idea_id text, p_status text)'),
      ('authenticated', 'public.approve_team_request(p_id text, p_status text, p_note text)'),
      ('authenticated', 'public.cache_get(p_key text)'),
      ('authenticated', 'public.cache_set(p_key text, p_value text, p_ttl integer)'),
      ('authenticated', 'public.calculate_incentive(p_nrp text)'),
      ('authenticated', 'public.change_password(p_nrp text, p_old_password text, p_new_password text)'),
      ('authenticated', 'public.check_login_lockout(p_identifier text, p_attempt_type text)'),
      ('authenticated', 'public.check_module_access(p_module_code text, p_required_role_level integer)'),
      ('authenticated', 'public.check_owner_identity()'),
      ('authenticated', 'public.checkin_asset(p_asset_id text, p_condition text)'),
      ('authenticated', 'public.checkout_asset(p_asset_id text, p_nrp text)'),
      ('authenticated', 'public.create_forum_post(p_nrp text, p_title text, p_content text, p_category text)'),
      ('authenticated', 'public.create_okr(p_nrp text, p_periode text, p_objective text)'),
      ('authenticated', 'public.create_task(p_assignee text, p_title text, p_due date)'),
      ('authenticated', 'public.create_task(p_nrp text, p_assigner text, p_title text, p_desc text, p_priority text, p_due date)'),
      ('authenticated', 'public.create_worker_request(p_nrp text, p_type text, p_detail text, p_note text)'),
      ('authenticated', 'public.create_worker_request(p_nrp text, p_type text, p_reason text, p_from date, p_to date)'),
      ('authenticated', 'public.generate_admin_otp()'),
      ('authenticated', 'public.generate_worker_otp(p_nrp text, p_nik text)'),
      ('authenticated', 'public.generate_worker_otp(p_nrp text, p_nik text, p_password text)'),
      ('authenticated', 'public.get_active_sessions()'),
      ('authenticated', 'public.get_announcements()'),
      ('authenticated', 'public.get_anomaly_sentinel()'),
      ('authenticated', 'public.get_audit_log_actions()'),
      ('authenticated', 'public.get_audit_log_owner(p_limit integer)'),
      ('authenticated', 'public.get_audit_log_v2(p_action_type text, p_from timestamp with time zone, p_to timestamp with time zone, p_limit integer, p_offset integer)'),
      ('authenticated', 'public.get_auto_healing_actions()'),
      ('authenticated', 'public.get_boiler_status(p_site_code text)'),
      ('authenticated', 'public.get_branding()'),
      ('authenticated', 'public.get_breakdown_log(p_limit integer)'),
      ('authenticated', 'public.get_business_units_for_owner()'),
      ('authenticated', 'public.get_candidate_pipeline(p_vacancy_id text)'),
      ('authenticated', 'public.get_career_path(p_nrp text)'),
      ('authenticated', 'public.get_company_config()'),
      ('authenticated', 'public.get_continuous_perf_team(p_nrp text)'),
      ('authenticated', 'public.get_current_user_context()'),
      ('authenticated', 'public.get_dashboard_stats()'),
      ('authenticated', 'public.get_early_warning()'),
      ('authenticated', 'public.get_enabled_modules()'),
      ('authenticated', 'public.get_estate_blocks()'),
      ('authenticated', 'public.get_estate_blocks(p_page integer, p_limit integer)'),
      ('authenticated', 'public.get_executive_summary()'),
      ('authenticated', 'public.get_fatigue_data(p_nrp text)'),
      ('authenticated', 'public.get_flight_risk_list()'),
      ('authenticated', 'public.get_forum_posts()'),
      ('authenticated', 'public.get_harvest_records()'),
      ('authenticated', 'public.get_heavy_equipment(p_nrp text)'),
      ('authenticated', 'public.get_incentives(p_nrp text)'),
      ('authenticated', 'public.get_industry_admin_stats(p_industry text)'),
      ('authenticated', 'public.get_jsa_list(p_nrp text)'),
      ('authenticated', 'public.get_kpi_by_division()'),
      ('authenticated', 'public.get_login_attempt_stats()'),
      ('authenticated', 'public.get_maintenance_schedule(p_status text)'),
      ('authenticated', 'public.get_medical_checkup(p_nrp text)'),
      ('authenticated', 'public.get_modules_for_owner()'),
      ('authenticated', 'public.get_my_okrs(p_nrp text)'),
      ('authenticated', 'public.get_notification_config()'),
      ('authenticated', 'public.get_offboarding_checklist(p_nrp text)'),
      ('authenticated', 'public.get_onboarding_tasks(p_nrp text)'),
      ('authenticated', 'public.get_owner_employees_by_bu()'),
      ('authenticated', 'public.get_owner_overview_stats()'),
      ('authenticated', 'public.get_packing_log(p_limit integer)'),
      ('authenticated', 'public.get_performance_notes(p_nrp text)'),
      ('authenticated', 'public.get_pkwt_expiry_alert()'),
      ('authenticated', 'public.get_press_status(p_site_code text)'),
      ('authenticated', 'public.get_production_daily(p_nrp text)'),
      ('authenticated', 'public.get_qc_results(p_limit integer)'),
      ('authenticated', 'public.get_reviews_360(p_nrp text)'),
      ('authenticated', 'public.get_role_overview()'),
      ('authenticated', 'public.get_safety_incidents(p_nrp text)'),
      ('authenticated', 'public.get_screening_results()'),
      ('authenticated', 'public.get_shift_assignments(p_date date, p_shift text)'),
      ('authenticated', 'public.get_shift_schedule()'),
      ('authenticated', 'public.get_simper_list(p_nrp text)'),
      ('authenticated', 'public.get_simulations()'),
      ('authenticated', 'public.get_skills_intelligence(p_nrp text)'),
      ('authenticated', 'public.get_succession(p_nrp text)'),
      ('authenticated', 'public.get_survey_results(p_survey_id integer)'),
      ('authenticated', 'public.get_talent_marketplace()'),
      ('authenticated', 'public.get_task_board(p_nrp text)'),
      ('authenticated', 'public.get_team_data(p_nrp text)'),
      ('authenticated', 'public.get_team_narrative(p_nrp text)'),
      ('authenticated', 'public.get_team_requests(p_nrp text)'),
      ('authenticated', 'public.get_transport_dispatch()'),
      ('authenticated', 'public.get_turnover_prediction()'),
      ('authenticated', 'public.get_user_context_by_auth_id(p_auth_id uuid)'),
      ('authenticated', 'public.get_whistleblowers()'),
      ('authenticated', 'public.get_worker_activities(p_nrp text)'),
      ('authenticated', 'public.get_worker_attendance(p_nrp text)'),
      ('authenticated', 'public.get_worker_badges(p_nrp text)'),
      ('authenticated', 'public.get_worker_benefits(p_nrp text)'),
      ('authenticated', 'public.get_worker_certifications(p_nrp text)'),
      ('authenticated', 'public.get_worker_kpi(p_nrp text)'),
      ('authenticated', 'public.get_worker_learning(p_nrp text)'),
      ('authenticated', 'public.get_worker_leave(p_nrp text)'),
      ('authenticated', 'public.get_worker_narrative(p_nrp text)'),
      ('authenticated', 'public.get_worker_overtime(p_nrp text)'),
      ('authenticated', 'public.get_worker_payroll(p_nrp text)'),
      ('authenticated', 'public.get_worker_profile(p_nrp text)'),
      ('authenticated', 'public.get_worker_referrals(p_nrp text)'),
      ('authenticated', 'public.get_worker_requests()'),
      ('authenticated', 'public.get_worker_requests(p_nrp text)'),
      ('authenticated', 'public.get_worker_status(p_nrp text)'),
      ('authenticated', 'public.get_workforce_planning()'),
      ('authenticated', 'public.list_ideas()'),
      ('authenticated', 'public.list_ideas(p_nrp text)'),
      ('authenticated', 'public.login_admin(p_password text)'),
      ('authenticated', 'public.login_worker(p_nrp text, p_nik text, p_password text)'),
      ('authenticated', 'public.login_worker(p_nrp text, p_password text)'),
      ('authenticated', 'public.move_candidate(p_id text, p_stage text)'),
      ('authenticated', 'public.owner_assign_admin_user(p_nrp text, p_role_code text)'),
      ('authenticated', 'public.owner_create_admin_role(p_role_code text, p_role_name text, p_scope_type text, p_scope_id text, p_permissions jsonb)'),
      ('authenticated', 'public.owner_create_announcement(p_title text, p_message text, p_priority text, p_target_audience text, p_expiry_date date)'),
      ('authenticated', 'public.owner_create_bu(p_unit_code text, p_unit_name text, p_description text)'),
      ('authenticated', 'public.owner_create_employee(p_nrp text, p_nama text, p_email text, p_divisi text, p_posisi text, p_bu_id text, p_status_kerja text, p_role text, p_role_level integer)'),
      ('authenticated', 'public.owner_create_integration(p_name text, p_type text, p_config jsonb)'),
      ('authenticated', 'public.owner_create_system_announcement(p_title text, p_message text, p_type text, p_dismissible boolean, p_end_at timestamp with time zone)'),
      ('authenticated', 'public.owner_deactivate_employee(p_nrp text)'),
      ('authenticated', 'public.owner_delete_announcement(p_id text)'),
      ('authenticated', 'public.owner_delete_bu(p_bu_id text)'),
      ('authenticated', 'public.owner_delete_integration(p_id text)'),
      ('authenticated', 'public.owner_delete_system_announcement(p_id text)'),
      ('authenticated', 'public.owner_force_logout(p_nrp text)'),
      ('authenticated', 'public.owner_get_activity_stats()'),
      ('authenticated', 'public.owner_get_admin_accounts()'),
      ('authenticated', 'public.owner_get_admin_roles()'),
      ('authenticated', 'public.owner_get_announcements()'),
      ('authenticated', 'public.owner_get_changelog()'),
      ('authenticated', 'public.owner_get_employees(p_bu_id text, p_search text, p_limit integer, p_offset integer)'),
      ('authenticated', 'public.owner_get_integrations()'),
      ('authenticated', 'public.owner_get_retention_rules()'),
      ('authenticated', 'public.owner_get_security_settings()'),
      ('authenticated', 'public.owner_get_system_announcements()'),
      ('authenticated', 'public.owner_get_tickets()'),
      ('authenticated', 'public.owner_get_usage_analytics()'),
      ('authenticated', 'public.owner_login(p_email text)'),
      ('authenticated', 'public.owner_set_tier(p_bu_id text, p_tier integer)'),
      ('authenticated', 'public.owner_toggle_lock(p_module_code text, p_enable boolean)'),
      ('authenticated', 'public.owner_toggle_lock(p_module_code text, p_enable boolean, p_bu_id text)'),
      ('authenticated', 'public.owner_update_admin_role(p_role_id integer, p_role_name text, p_permissions jsonb, p_is_active boolean)'),
      ('authenticated', 'public.owner_update_bu(p_bu_id text, p_unit_name text, p_description text, p_is_active boolean)'),
      ('authenticated', 'public.owner_update_retention_rule(p_id text, p_retention_days integer, p_archive_enabled boolean)'),
      ('authenticated', 'public.owner_update_role(p_nrp text, p_role text, p_role_level integer)'),
      ('authenticated', 'public.owner_update_ticket_status(p_ticket_id text, p_status text, p_assigned_to text)'),
      ('authenticated', 'public.process_request(p_request_id text, p_action text, p_approver text, p_note text)'),
      ('authenticated', 'public.register_session(p_session_id text, p_ip text, p_ua text)'),
      ('authenticated', 'public.reply_forum_post(p_post_id uuid, p_nrp text, p_content text)'),
      ('authenticated', 'public.reset_password(p_nrp text, p_token text, p_new_password text)'),
      ('authenticated', 'public.run_simulation(p_turnover_change numeric)'),
      ('authenticated', 'public.submit_idea(p_nrp text, p_title text, p_description text, p_category text)'),
      ('authenticated', 'public.submit_request(p_nrp text, p_type text, p_details text)'),
      ('authenticated', 'public.submit_survey(p_survey_id integer, p_nrp text, p_answers jsonb, p_score integer)'),
      ('authenticated', 'public.submit_whistleblower(p_category text, p_desc text)'),
      ('authenticated', 'public.update_branding(p_company_name text, p_tagline text, p_logo_url text, p_primary_color text)'),
      ('authenticated', 'public.update_company_config(p_config_id text, p_value jsonb)'),
      ('authenticated', 'public.update_notification_config(p_id text, p_email_enabled boolean, p_push_enabled boolean)'),
      ('authenticated', 'public.update_task_status(p_id integer, p_status text)'),
      ('authenticated', 'public.update_task_status(p_task_id text, p_status text)'),
      ('authenticated', 'public.verify_admin_otp(p_code text)'),
      ('authenticated', 'public.verify_worker_otp(p_nrp text, p_code text)'),
      ('authenticated', 'public.vote_idea(p_idea_id text)'),
      ('authenticated', 'public.worker_change_password(p_nrp text, p_old text, p_new text)'),
      ('authenticated', 'public.worker_logout()'),
      ('authenticated', 'public.worker_update_profile(p_nrp text, p_email text, p_no_hp text, p_alamat text)')
    ) AS t(role_name, sig)
  LOOP
    BEGIN
      EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO %I', r.sig, r.role_name);
    EXCEPTION WHEN undefined_function THEN
      n_missing := n_missing + 1;
      RAISE NOTICE '172: lewati GRANT % -> % (fungsi tidak ada pada instalasi ini)', r.sig, r.role_name;
    END;
  END LOOP;
  IF n_missing > 0 THEN RAISE NOTICE '172: % grant dilewati karena fungsinya tidak ada', n_missing; END IF;
END $grant172$;

-- 5) Cek hasil (read-only, fungsi non-ekstensi saja — ACL fungsi pgvector)
--    dikelola supabase_admin dan tidak bisa di-revoke dari role pooler (no-op senyap))
SELECT 'total_fungsi_non_ext' AS ukuran, count(*)::text AS jumlah FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prokind='f' AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid='pg_proc'::regclass AND d.objid=p.oid AND d.refclassid='pg_extension'::regclass AND d.deptype='e')
UNION ALL SELECT 'callable_anon', count(*)::text FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prokind='f' AND has_function_privilege('anon',p.oid,'EXECUTE') AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid='pg_proc'::regclass AND d.objid=p.oid AND d.refclassid='pg_extension'::regclass AND d.deptype='e')
UNION ALL SELECT 'callable_authenticated', count(*)::text FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prokind='f' AND has_function_privilege('authenticated',p.oid,'EXECUTE') AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid='pg_proc'::regclass AND d.objid=p.oid AND d.refclassid='pg_extension'::regclass AND d.deptype='e')
UNION ALL SELECT 'callable_service_role', count(*)::text FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prokind='f' AND has_function_privilege('service_role',p.oid,'EXECUTE') AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid='pg_proc'::regclass AND d.objid=p.oid AND d.refclassid='pg_extension'::regclass AND d.deptype='e')
UNION ALL SELECT 'decrypt/export/owner_* non-ext tertutup anon+auth', count(*)::text FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prokind='f' AND (p.proname='decrypt_pii' OR p.proname LIKE 'export\_%' OR p.proname LIKE 'owner\_%') AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND NOT has_function_privilege('authenticated',p.oid,'EXECUTE');
